	usedinvClicking[0] = TextDrawCreate(389.321075, 154.416809, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[0], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[0], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[0], 1);
	TextDrawColor(usedinvClicking[0], -1);
	TextDrawSetShadow(usedinvClicking[0], 0);
	TextDrawSetOutline(usedinvClicking[0], 0);
	TextDrawFont(usedinvClicking[0], 4);
	TextDrawSetSelectable(usedinvClicking[0], 1);

	usedinvClicking[1] = TextDrawCreate(468.095611, 154.250152, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[1], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[1], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[1], 1);
	TextDrawColor(usedinvClicking[1], -1);
	TextDrawSetShadow(usedinvClicking[1], 0);
	TextDrawSetOutline(usedinvClicking[1], 0);
	TextDrawFont(usedinvClicking[1], 4);
	TextDrawSetSelectable(usedinvClicking[1], 1);

	usedinvClicking[2] = TextDrawCreate(388.978454, 184.416809, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[2], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[2], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[2], 1);
	TextDrawColor(usedinvClicking[2], -1);
	TextDrawSetShadow(usedinvClicking[2], 0);
	TextDrawSetOutline(usedinvClicking[2], 0);
	TextDrawFont(usedinvClicking[2], 4);
	TextDrawSetSelectable(usedinvClicking[2], 1);

	usedinvClicking[3] = TextDrawCreate(468.221710, 184.833465, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[3], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[3], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[3], 1);
	TextDrawColor(usedinvClicking[3], -1);
	TextDrawSetShadow(usedinvClicking[3], 0);
	TextDrawSetOutline(usedinvClicking[3], 0);
	TextDrawFont(usedinvClicking[3], 4);
	TextDrawSetSelectable(usedinvClicking[3], 1);

	usedinvClicking[4] = TextDrawCreate(389.104461, 215.000122, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[4], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[4], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[4], 1);
	TextDrawColor(usedinvClicking[4], -1);
	TextDrawSetShadow(usedinvClicking[4], 0);
	TextDrawSetOutline(usedinvClicking[4], 0);
	TextDrawFont(usedinvClicking[4], 4);
	TextDrawSetSelectable(usedinvClicking[4], 1);

	usedinvClicking[5] = TextDrawCreate(468.347717, 214.833465, "LD_SPAC:white");
	TextDrawLetterSize(usedinvClicking[5], 0.000000, 0.000000);
	TextDrawTextSize(usedinvClicking[5], 22.489028, 25.666656);
	TextDrawAlignment(usedinvClicking[5], 1);
	TextDrawColor(usedinvClicking[5], -1);
	TextDrawSetShadow(usedinvClicking[5], 0);
	TextDrawSetOutline(usedinvClicking[5], 0);
	TextDrawFont(usedinvClicking[5], 4);
	TextDrawSetSelectable(usedinvClicking[5], 1);

	//

	inv_clickingTD[0] = TextDrawCreate(147.115661, 142.333343, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[0], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[0], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[0], 1);
	TextDrawColor(inv_clickingTD[0], -1);
	TextDrawSetShadow(inv_clickingTD[0], 0);
	TextDrawSetOutline(inv_clickingTD[0], 0);
	TextDrawFont(inv_clickingTD[0], 4);
	TextDrawSetSelectable(inv_clickingTD[0], 1);

	inv_clickingTD[1] = TextDrawCreate(194.499267, 142.166687, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[1], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[1], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[1], 1);
	TextDrawColor(inv_clickingTD[1], -1);
	TextDrawSetShadow(inv_clickingTD[1], 0);
	TextDrawSetOutline(inv_clickingTD[1], 0);
	TextDrawFont(inv_clickingTD[1], 4);
	TextDrawSetSelectable(inv_clickingTD[1], 1);

	inv_clickingTD[2] = TextDrawCreate(241.414337, 142.000030, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[2], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[2], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[2], 1);
	TextDrawColor(inv_clickingTD[2], -1);
	TextDrawSetShadow(inv_clickingTD[2], 0);
	TextDrawSetOutline(inv_clickingTD[2], 0);
	TextDrawFont(inv_clickingTD[2], 4);
	TextDrawSetSelectable(inv_clickingTD[2], 1);

	inv_clickingTD[3] = TextDrawCreate(288.329406, 142.416702, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[3], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[3], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[3], 1);
	TextDrawColor(inv_clickingTD[3], -1);
	TextDrawSetShadow(inv_clickingTD[3], 0);
	TextDrawSetOutline(inv_clickingTD[3], 0);
	TextDrawFont(inv_clickingTD[3], 4);
	TextDrawSetSelectable(inv_clickingTD[3], 1);

	inv_clickingTD[4] = TextDrawCreate(335.244476, 142.833374, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[4], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[4], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[4], 1);
	TextDrawColor(inv_clickingTD[4], -1);
	TextDrawSetShadow(inv_clickingTD[4], 0);
	TextDrawSetOutline(inv_clickingTD[4], 0);
	TextDrawFont(inv_clickingTD[4], 4);
	TextDrawSetSelectable(inv_clickingTD[4], 1);

	inv_clickingTD[5] = TextDrawCreate(147.430419, 191.083419, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[5], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[5], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[5], 1);
	TextDrawColor(inv_clickingTD[5], -1);
	TextDrawSetShadow(inv_clickingTD[5], 0);
	TextDrawSetOutline(inv_clickingTD[5], 0);
	TextDrawFont(inv_clickingTD[5], 4);
	TextDrawSetSelectable(inv_clickingTD[5], 1);

	inv_clickingTD[6] = TextDrawCreate(194.814010, 190.916732, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[6], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[6], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[6], 1);
	TextDrawColor(inv_clickingTD[6], -1);
	TextDrawSetShadow(inv_clickingTD[6], 0);
	TextDrawSetOutline(inv_clickingTD[6], 0);
	TextDrawFont(inv_clickingTD[6], 4);
	TextDrawSetSelectable(inv_clickingTD[6], 1);

	inv_clickingTD[7] = TextDrawCreate(241.729080, 191.333404, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[7], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[7], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[7], 1);
	TextDrawColor(inv_clickingTD[7], -1);
	TextDrawSetShadow(inv_clickingTD[7], 0);
	TextDrawSetOutline(inv_clickingTD[7], 0);
	TextDrawFont(inv_clickingTD[7], 4);
	TextDrawSetSelectable(inv_clickingTD[7], 1);

	inv_clickingTD[8] = TextDrawCreate(288.175720, 191.166748, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[8], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[8], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[8], 1);
	TextDrawColor(inv_clickingTD[8], -1);
	TextDrawSetShadow(inv_clickingTD[8], 0);
	TextDrawSetOutline(inv_clickingTD[8], 0);
	TextDrawFont(inv_clickingTD[8], 4);
	TextDrawSetSelectable(inv_clickingTD[8], 1);

	inv_clickingTD[9] = TextDrawCreate(335.090789, 191.000076, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[9], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[9], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[9], 1);
	TextDrawColor(inv_clickingTD[9], -1);
	TextDrawSetShadow(inv_clickingTD[9], 0);
	TextDrawSetOutline(inv_clickingTD[9], 0);
	TextDrawFont(inv_clickingTD[9], 4);
	TextDrawSetSelectable(inv_clickingTD[9], 1);

	inv_clickingTD[10] = TextDrawCreate(146.808181, 239.833404, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[10], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[10], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[10], 1);
	TextDrawColor(inv_clickingTD[10], -1);
	TextDrawSetShadow(inv_clickingTD[10], 0);
	TextDrawSetOutline(inv_clickingTD[10], 0);
	TextDrawFont(inv_clickingTD[10], 4);
	TextDrawSetSelectable(inv_clickingTD[10], 1);

	inv_clickingTD[11] = TextDrawCreate(194.191772, 240.250091, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[11], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[11], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[11], 1);
	TextDrawColor(inv_clickingTD[11], -1);
	TextDrawSetShadow(inv_clickingTD[11], 0);
	TextDrawSetOutline(inv_clickingTD[11], 0);
	TextDrawFont(inv_clickingTD[11], 4);
	TextDrawSetSelectable(inv_clickingTD[11], 1);

	inv_clickingTD[12] = TextDrawCreate(241.575347, 240.083435, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[12], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[12], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[12], 1);
	TextDrawColor(inv_clickingTD[12], -1);
	TextDrawSetShadow(inv_clickingTD[12], 0);
	TextDrawSetOutline(inv_clickingTD[12], 0);
	TextDrawFont(inv_clickingTD[12], 4);
	TextDrawSetSelectable(inv_clickingTD[12], 1);

	inv_clickingTD[13] = TextDrawCreate(288.490386, 239.916763, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[13], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[13], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[13], 1);
	TextDrawColor(inv_clickingTD[13], -1);
	TextDrawSetShadow(inv_clickingTD[13], 0);
	TextDrawSetOutline(inv_clickingTD[13], 0);
	TextDrawFont(inv_clickingTD[13], 4);
	TextDrawSetSelectable(inv_clickingTD[13], 1);

	inv_clickingTD[14] = TextDrawCreate(334.937103, 240.333435, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[14], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[14], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[14], 1);
	TextDrawColor(inv_clickingTD[14], -1);
	TextDrawSetShadow(inv_clickingTD[14], 0);
	TextDrawSetOutline(inv_clickingTD[14], 0);
	TextDrawFont(inv_clickingTD[14], 4);
	TextDrawSetSelectable(inv_clickingTD[14], 1);

	inv_clickingTD[15] = TextDrawCreate(146.654525, 289.166778, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[15], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[15], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[15], 1);
	TextDrawColor(inv_clickingTD[15], -1);
	TextDrawSetShadow(inv_clickingTD[15], 0);
	TextDrawSetOutline(inv_clickingTD[15], 0);
	TextDrawFont(inv_clickingTD[15], 4);
	TextDrawSetSelectable(inv_clickingTD[15], 1);

	inv_clickingTD[16] = TextDrawCreate(194.506637, 289.000122, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[16], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[16], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[16], 1);
	TextDrawColor(inv_clickingTD[16], -1);
	TextDrawSetShadow(inv_clickingTD[16], 0);
	TextDrawSetOutline(inv_clickingTD[16], 0);
	TextDrawFont(inv_clickingTD[16], 4);
	TextDrawSetSelectable(inv_clickingTD[16], 1);

	inv_clickingTD[17] = TextDrawCreate(241.421707, 288.833435, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[17], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[17], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[17], 1);
	TextDrawColor(inv_clickingTD[17], -1);
	TextDrawSetShadow(inv_clickingTD[17], 0);
	TextDrawSetOutline(inv_clickingTD[17], 0);
	TextDrawFont(inv_clickingTD[17], 4);
	TextDrawSetSelectable(inv_clickingTD[17], 1);

	inv_clickingTD[18] = TextDrawCreate(288.337005, 289.250152, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[18], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[18], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[18], 1);
	TextDrawColor(inv_clickingTD[18], -1);
	TextDrawSetShadow(inv_clickingTD[18], 0);
	TextDrawSetOutline(inv_clickingTD[18], 0);
	TextDrawFont(inv_clickingTD[18], 4);
	TextDrawSetSelectable(inv_clickingTD[18], 1);

	inv_clickingTD[19] = TextDrawCreate(334.783630, 289.083435, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[19], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[19], 42.635437, 44.916656);
	TextDrawAlignment(inv_clickingTD[19], 1);
	TextDrawColor(inv_clickingTD[19], -1);
	TextDrawSetShadow(inv_clickingTD[19], 0);
	TextDrawSetOutline(inv_clickingTD[19], 0);
	TextDrawFont(inv_clickingTD[19], 4);
	TextDrawSetSelectable(inv_clickingTD[19], 1);

	inv_clickingTD[20] = TextDrawCreate(209.751419, 343.750152, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[20], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[20], 50.131774, 14.583326);
	TextDrawAlignment(inv_clickingTD[20], 1);
	TextDrawColor(inv_clickingTD[20], -1);
	TextDrawSetShadow(inv_clickingTD[20], 0);
	TextDrawSetOutline(inv_clickingTD[20], 0);
	TextDrawFont(inv_clickingTD[20], 4);
	TextDrawSetSelectable(inv_clickingTD[20], 1);

	inv_clickingTD[21] = TextDrawCreate(266.037017, 344.166809, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[21], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[21], 50.131774, 14.583326);
	TextDrawAlignment(inv_clickingTD[21], 1);
	TextDrawColor(inv_clickingTD[21], -1);
	TextDrawSetShadow(inv_clickingTD[21], 0);
	TextDrawSetOutline(inv_clickingTD[21], 0);
	TextDrawFont(inv_clickingTD[21], 4);
	TextDrawSetSelectable(inv_clickingTD[21], 1);

	inv_clickingTD[22] = TextDrawCreate(397.286132, 324.750061, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[22], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[22], 42.635437, 13.999993);
	TextDrawAlignment(inv_clickingTD[22], 1);
	TextDrawColor(inv_clickingTD[22], -1);
	TextDrawSetShadow(inv_clickingTD[22], 0);
	TextDrawSetOutline(inv_clickingTD[22], 0);
	TextDrawFont(inv_clickingTD[22], 4);
	TextDrawSetSelectable(inv_clickingTD[22], 1);

	inv_clickingTD[23] = TextDrawCreate(396.880523, 344.416748, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[23], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[23], 42.635437, 13.999993);
	TextDrawAlignment(inv_clickingTD[23], 1);
	TextDrawColor(inv_clickingTD[23], -1);
	TextDrawSetShadow(inv_clickingTD[23], 0);
	TextDrawSetOutline(inv_clickingTD[23], 0);
	TextDrawFont(inv_clickingTD[23], 4);
	TextDrawSetSelectable(inv_clickingTD[23], 1);

	inv_clickingTD[24] = TextDrawCreate(443.795684, 324.416717, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[24], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[24], 42.635437, 13.999993);
	TextDrawAlignment(inv_clickingTD[24], 1);
	TextDrawColor(inv_clickingTD[24], -1);
	TextDrawSetShadow(inv_clickingTD[24], 0);
	TextDrawSetOutline(inv_clickingTD[24], 0);
	TextDrawFont(inv_clickingTD[24], 4);
	TextDrawSetSelectable(inv_clickingTD[24], 1);

	inv_clickingTD[25] = TextDrawCreate(443.858764, 344.083404, "LD_SPAC:white");
	TextDrawLetterSize(inv_clickingTD[25], 0.000000, 0.000000);
	TextDrawTextSize(inv_clickingTD[25], 42.635437, 13.999993);
	TextDrawAlignment(inv_clickingTD[25], 1);
	TextDrawColor(inv_clickingTD[25], -1);
	TextDrawSetShadow(inv_clickingTD[25], 0);
	TextDrawSetOutline(inv_clickingTD[25], 0);
	TextDrawFont(inv_clickingTD[25], 4);
	TextDrawSetSelectable(inv_clickingTD[25], 1);

	//	

	global_invTD[0] = TextDrawCreate(142.898971, 118.999931, "vehicle:vehicleenvmap128");
	TextDrawLetterSize(global_invTD[0], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[0], 356.513305, 243.833480);
	TextDrawAlignment(global_invTD[0], 2);
	TextDrawColor(global_invTD[0], -1256502529);
	TextDrawSetShadow(global_invTD[0], 0);
	TextDrawSetOutline(global_invTD[0], 0);
	TextDrawFont(global_invTD[0], 4);

	global_invTD[1] = TextDrawCreate(501.006713, 121.083328, "usebox");
	TextDrawLetterSize(global_invTD[1], 0.000000, 26.585365);
	TextDrawTextSize(global_invTD[1], 140.898986, 0.000000);
	TextDrawAlignment(global_invTD[1], 1);
	TextDrawColor(global_invTD[1], -1);
	TextDrawUseBox(global_invTD[1], true);
	TextDrawBoxColor(global_invTD[1], -989711958);
	TextDrawSetShadow(global_invTD[1], 0);
	TextDrawSetOutline(global_invTD[1], 0);
	TextDrawBackgroundColor(global_invTD[1], -1);
	TextDrawFont(global_invTD[1], 0);

	global_invTD[2] = TextDrawCreate(140.245407, 113.044334, "ld_beat:chit");
	TextDrawLetterSize(global_invTD[2], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[2], 14.524145, 14.622220);
	TextDrawAlignment(global_invTD[2], 1);
	TextDrawColor(global_invTD[2], -2080300545);
	TextDrawSetShadow(global_invTD[2], 0);
	TextDrawSetOutline(global_invTD[2], 0);
	TextDrawFont(global_invTD[2], 4);

	global_invTD[3] = TextDrawCreate(487.245422, 113.044448, "ld_beat:chit");
	TextDrawLetterSize(global_invTD[3], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[3], 14.524145, 13.999999);
	TextDrawAlignment(global_invTD[3], 1);
	TextDrawColor(global_invTD[3], -2080300545);
	TextDrawSetShadow(global_invTD[3], 0);
	TextDrawSetOutline(global_invTD[3], 0);
	TextDrawFont(global_invTD[3], 4);

	global_invTD[4] = TextDrawCreate(486.888122, 356.122192, "ld_beat:chit");
	TextDrawLetterSize(global_invTD[4], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[4], 14.524145, 13.999999);
	TextDrawAlignment(global_invTD[4], 1);
	TextDrawColor(global_invTD[4], -2080300545);
	TextDrawSetShadow(global_invTD[4], 0);
	TextDrawSetOutline(global_invTD[4], 0);
	TextDrawFont(global_invTD[4], 4);

	global_invTD[5] = TextDrawCreate(140.245407, 355.994445, "ld_beat:chit");
	TextDrawLetterSize(global_invTD[5], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[5], 14.524145, 13.999999);
	TextDrawAlignment(global_invTD[5], 1);
	TextDrawColor(global_invTD[5], -2080300545);
	TextDrawSetShadow(global_invTD[5], 0);
	TextDrawSetOutline(global_invTD[5], 0);
	TextDrawFont(global_invTD[5], 4);

	global_invTD[6] = TextDrawCreate(147.115661, 115.500000, "LD_SPAC:white");
	TextDrawLetterSize(global_invTD[6], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[6], 346.642730, 29.166688);
	TextDrawAlignment(global_invTD[6], 1);
	TextDrawColor(global_invTD[6], -2080300545);
	TextDrawSetShadow(global_invTD[6], 0);
	TextDrawSetOutline(global_invTD[6], 0);
	TextDrawFont(global_invTD[6], 4);

	global_invTD[7] = TextDrawCreate(146.710098, 343.416625, "LD_SPAC:white");
	TextDrawLetterSize(global_invTD[7], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[7], 349.111267, 24.499994);
	TextDrawAlignment(global_invTD[7], 1);
	TextDrawColor(global_invTD[7], -2080300545);
	TextDrawSetShadow(global_invTD[7], 0);
	TextDrawSetOutline(global_invTD[7], 0);
	TextDrawFont(global_invTD[7], 4);

	global_invTD[8] = TextDrawCreate(142.898971, 138.250000, "LD_SPAC:white");
	TextDrawLetterSize(global_invTD[8], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[8], 356.544494, 1.166643);
	TextDrawAlignment(global_invTD[8], 1);
	TextDrawColor(global_invTD[8], -1);
	TextDrawSetShadow(global_invTD[8], 0);
	TextDrawSetOutline(global_invTD[8], 0);
	TextDrawFont(global_invTD[8], 4);

	global_invTD[9] = TextDrawCreate(381.376281, 119.000000, "LD_SPAC:white");
	TextDrawLetterSize(global_invTD[9], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[9], 0.937025, 245.583312);
	TextDrawAlignment(global_invTD[9], 1);
	TextDrawColor(global_invTD[9], -1);
	TextDrawSetShadow(global_invTD[9], 0);
	TextDrawSetOutline(global_invTD[9], 0);
	TextDrawFont(global_invTD[9], 4);

	global_invTD[10] = TextDrawCreate(261.434783, 118.999977, "INVENTORY");
	TextDrawLetterSize(global_invTD[10], 0.250409, 1.500833);
	TextDrawAlignment(global_invTD[10], 2);
	TextDrawColor(global_invTD[10], -1);
	TextDrawSetShadow(global_invTD[10], 0);
	TextDrawSetOutline(global_invTD[10], 0);
	TextDrawBackgroundColor(global_invTD[10], 51);
	TextDrawFont(global_invTD[10], 2);
	TextDrawSetProportional(global_invTD[10], 1);

	global_invTD[11] = TextDrawCreate(440.941558, 118.833297, "PERSON");
	TextDrawLetterSize(global_invTD[11], 0.250409, 1.500833);
	TextDrawAlignment(global_invTD[11], 2);
	TextDrawColor(global_invTD[11], -1);
	TextDrawSetShadow(global_invTD[11], 0);
	TextDrawSetOutline(global_invTD[11], 0);
	TextDrawBackgroundColor(global_invTD[11], 51);
	TextDrawFont(global_invTD[11], 2);
	TextDrawSetProportional(global_invTD[11], 1);

	global_invTD[12] = TextDrawCreate(262.029479, 345.666687, "usebox");
	TextDrawLetterSize(global_invTD[12], 0.000000, 1.217033);
	TextDrawTextSize(global_invTD[12], 207.429183, 0.000000);
	TextDrawAlignment(global_invTD[12], 1);
	TextDrawColor(global_invTD[12], 0);
	TextDrawUseBox(global_invTD[12], true);
	TextDrawBoxColor(global_invTD[12], 16843178);
	TextDrawSetShadow(global_invTD[12], 0);
	TextDrawSetOutline(global_invTD[12], 0);
	TextDrawFont(global_invTD[12], 0);

	global_invTD[13] = TextDrawCreate(318.315185, 345.499877, "usebox");
	TextDrawLetterSize(global_invTD[13], 0.000000, 1.217033);
	TextDrawTextSize(global_invTD[13], 263.651824, 0.000000);
	TextDrawAlignment(global_invTD[13], 1);
	TextDrawColor(global_invTD[13], 0);
	TextDrawUseBox(global_invTD[13], true);
	TextDrawBoxColor(global_invTD[13], 16843178);
	TextDrawSetShadow(global_invTD[13], 0);
	TextDrawSetOutline(global_invTD[13], 0);
	TextDrawFont(global_invTD[13], 0);

	global_invTD[14] = TextDrawCreate(442.239135, 345.416717, "usebox");
	TextDrawLetterSize(global_invTD[14], 0.000000, 1.251829);
	TextDrawTextSize(global_invTD[14], 394.731628, 0.000000);
	TextDrawAlignment(global_invTD[14], 1);
	TextDrawColor(global_invTD[14], 0);
	TextDrawUseBox(global_invTD[14], true);
	TextDrawBoxColor(global_invTD[14], 16843178);
	TextDrawSetShadow(global_invTD[14], 0);
	TextDrawSetOutline(global_invTD[14], 0);
	TextDrawFont(global_invTD[14], 3);

	global_invTD[15] = TextDrawCreate(441.833526, 326.583526, "usebox");
	TextDrawLetterSize(global_invTD[15], 0.000000, 1.204975);
	TextDrawTextSize(global_invTD[15], 394.731628, 0.000000);
	TextDrawAlignment(global_invTD[15], 1);
	TextDrawColor(global_invTD[15], 0);
	TextDrawUseBox(global_invTD[15], true);
	TextDrawBoxColor(global_invTD[15], 16843178);
	TextDrawSetShadow(global_invTD[15], 0);
	TextDrawSetOutline(global_invTD[15], 0);
	TextDrawFont(global_invTD[15], 3);

	global_invTD[16] = TextDrawCreate(488.748565, 326.416687, "usebox");
	TextDrawLetterSize(global_invTD[16], 0.000000, 1.251829);
	TextDrawTextSize(global_invTD[16], 441.583709, 0.000000);
	TextDrawAlignment(global_invTD[16], 1);
	TextDrawColor(global_invTD[16], 0);
	TextDrawUseBox(global_invTD[16], true);
	TextDrawBoxColor(global_invTD[16], 16843178);
	TextDrawSetShadow(global_invTD[16], 0);
	TextDrawSetOutline(global_invTD[16], 0);
	TextDrawFont(global_invTD[16], 3);

	global_invTD[17] = TextDrawCreate(488.685485, 345.833374, "usebox");
	TextDrawLetterSize(global_invTD[17], 0.000000, 1.204975);
	TextDrawTextSize(global_invTD[17], 441.583465, 0.000000);
	TextDrawAlignment(global_invTD[17], 1);
	TextDrawColor(global_invTD[17], 0);
	TextDrawUseBox(global_invTD[17], true);
	TextDrawBoxColor(global_invTD[17], 16843178);
	TextDrawSetShadow(global_invTD[17], 0);
	TextDrawSetOutline(global_invTD[17], 0);
	TextDrawFont(global_invTD[17], 3);

	global_invTD[18] = TextDrawCreate(396.368988, 247.333389, "ld_beat:chit");
	TextDrawLetterSize(global_invTD[18], 0.000000, 0.000000);
	TextDrawTextSize(global_invTD[18], 89.487586, 25.083326);
	TextDrawAlignment(global_invTD[18], 2);
	TextDrawColor(global_invTD[18], 1025056136);
	TextDrawSetShadow(global_invTD[18], 0);
	TextDrawSetOutline(global_invTD[18], 0);
	TextDrawFont(global_invTD[18], 4);

	global_invTD[19] = TextDrawCreate(215.114395, 343.999877, "DONATE");
	TextDrawLetterSize(global_invTD[19], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[19], 253.469909, 15.000000);
	TextDrawAlignment(global_invTD[19], 1);
	TextDrawColor(global_invTD[19], -1);
	TextDrawUseBox(global_invTD[19], true);
	TextDrawBoxColor(global_invTD[19], 0);
	TextDrawSetShadow(global_invTD[19], 0);
	TextDrawSetOutline(global_invTD[19], 0);
	TextDrawBackgroundColor(global_invTD[19], 51);
	TextDrawFont(global_invTD[19], 2);
	TextDrawSetProportional(global_invTD[19], 1);
	TextDrawSetSelectable(global_invTD[19], 1);

	global_invTD[20] = TextDrawCreate(277.490692, 343.833190, "MENU");
	TextDrawLetterSize(global_invTD[20], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[20], 303.601684, 15.000000);
	TextDrawAlignment(global_invTD[20], 1);
	TextDrawColor(global_invTD[20], -1);
	TextDrawUseBox(global_invTD[20], true);
	TextDrawBoxColor(global_invTD[20], 0);
	TextDrawSetShadow(global_invTD[20], 0);
	TextDrawSetOutline(global_invTD[20], 0);
	TextDrawBackgroundColor(global_invTD[20], 51);
	TextDrawFont(global_invTD[20], 2);
	TextDrawSetProportional(global_invTD[20], 1);
	TextDrawSetSelectable(global_invTD[20], 1);

	global_invTD[21] = TextDrawCreate(408.739624, 323.833160, "INFO");
	TextDrawLetterSize(global_invTD[21], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[21], 431.039642, 15.000000);
	TextDrawAlignment(global_invTD[21], 1);
	TextDrawColor(global_invTD[21], -1);
	TextDrawUseBox(global_invTD[21], true);
	TextDrawBoxColor(global_invTD[21], 0);
	TextDrawSetShadow(global_invTD[21], 0);
	TextDrawSetOutline(global_invTD[21], 0);
	TextDrawBackgroundColor(global_invTD[21], 51);
	TextDrawFont(global_invTD[21], 2);
	TextDrawSetProportional(global_invTD[21], 1);
	TextDrawSetSelectable(global_invTD[21], 1);

	global_invTD[22] = TextDrawCreate(452.843719, 324.249847, "DROP");
	TextDrawLetterSize(global_invTD[22], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[22], 477.891693, 15.000000);
	TextDrawAlignment(global_invTD[22], 1);
	TextDrawColor(global_invTD[22], -1);
	TextDrawUseBox(global_invTD[22], true);
	TextDrawBoxColor(global_invTD[22], 0);
	TextDrawSetShadow(global_invTD[22], 0);
	TextDrawSetOutline(global_invTD[22], 0);
	TextDrawBackgroundColor(global_invTD[22], 51);
	TextDrawFont(global_invTD[22], 2);
	TextDrawSetProportional(global_invTD[22], 1);
	TextDrawSetSelectable(global_invTD[22], 1);

	global_invTD[23] = TextDrawCreate(410.271423, 343.333160, "USE");
	TextDrawLetterSize(global_invTD[23], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[23], 429.165435, 15.000000);
	TextDrawAlignment(global_invTD[23], 1);
	TextDrawColor(global_invTD[23], -1);
	TextDrawUseBox(global_invTD[23], true);
	TextDrawBoxColor(global_invTD[23], 0);
	TextDrawSetShadow(global_invTD[23], 0);
	TextDrawSetOutline(global_invTD[23], 0);
	TextDrawBackgroundColor(global_invTD[23], 51);
	TextDrawFont(global_invTD[23], 2);
	TextDrawSetProportional(global_invTD[23], 1);
	TextDrawSetSelectable(global_invTD[23], 1);

	global_invTD[24] = TextDrawCreate(453.438385, 343.749816, "SELL");
	TextDrawLetterSize(global_invTD[24], 0.240571, 1.494999);
	TextDrawTextSize(global_invTD[24], 477.423187, 15.000000);
	TextDrawAlignment(global_invTD[24], 1);
	TextDrawColor(global_invTD[24], -1);
	TextDrawUseBox(global_invTD[24], true);
	TextDrawBoxColor(global_invTD[24], 0);
	TextDrawSetShadow(global_invTD[24], 0);
	TextDrawSetOutline(global_invTD[24], 0);
	TextDrawBackgroundColor(global_invTD[24], 51);
	TextDrawFont(global_invTD[24], 2);
	TextDrawSetProportional(global_invTD[24], 1);
	TextDrawSetSelectable(global_invTD[24], 1);